<script type="text/javascript">
var wpsymbolsCommentFormId='comment';

	var wpsymbols_more_symbols='[View More]';

	var wpsymbols_less_symbols='[View Less]';

	</script>
<script type="text/javascript" src="<?php echo get_option('siteurl');?>/wp-content/plugins/wpsymbols/tinymce/click.js"></script>
<style>	.wp_symbols {
	text-align: center;
	position:relative;
	height:0px;
}
.wp_symbols-content {
	width: 300px;
	padding: 3px;
	line-height: 120%;
	position:absolute;
	border: 1px solid #BFCAD2;
	background:#fff;
	left:160px;
	top:-100px;
	
}
.wp_symbol-button {
border: 1px solid #ccc;
margin: 1px;
padding: 2px;
}
.wp_symbol-button:hover {
cursor:pointer;
filter:progid:DXImageTransform.Microsoft.Alpha(opacity=60);
-moz-opacity: 0.6;
}</style>	
<img class="wp_symbol-button" src="<?php echo get_option('siteurl');?>/wp-content/plugins/wpsymbols/tinymce/1.gif" id="wpsymbols-select-symbol">
	<div class="wp_symbols">
            <div class="wp_symbols-content" style="display: none;">|


